### ISSUE TITLE
TO-DO v5.0

### ISSUE THREAD

**Issue by BeyondMagic** [BeyondMagic/nincat#4]
+ [x] `--add` **RETREATED:** Add art from file directly from `nincat` script and removes `fix_arts` script.
+ + It is better let the user solve this actually, as it is just the creation of a single file...
+ [x] `--random --center` print the art at the center of the terminal screen.
+ [x] `--random --left` **RETREATED:** print the art at the left of the terminal screen. Makes this the default.
+ + As default, by choosing no option, it will just print on the left.
+ [x] `--random --right` print the art at the right of the terminal screen.
+ [x] `--view $1 --match` **RETREATED:** enhancement to select file matching the same name. If multiple, just warns and exit.
+ + Replaced by `nincat --view "$(nincat --list | grep 'query')"`
+ [x] `--view $1 --raw` print the first line as well.
+ [x] Resolve unnecessary escape handling at the last character of the very last line when finished with `\`. Could be fixed at the `sed` call of `print_file` function or adding a new space there before adding the reset colouring.
+ [x] RETREATED: Remove `NOTES` numbers to instead hash so that adding new code isn't tiresome.
+ + No idea how to organize shell code better than this.
+ [x] `--random --raw` instead of `--random --see` and print the first line as well.

---

All of those features can be added without any loss to performance or speed.
